In [ ]:
def auction_to_numeric(z):
    if z=='ADESA':
        return 1
    if z=='MANHEIM':
        return 2
    else:
        return 0

def make_to_numeric(x):
    if x=='ACURA':
        return 1
    if x=='BUICK':
        return 2
    if x=='CADILLAC':
        return 3
    if x=='CHEVROLET':
        return 4
    if x=='CHRYSLER':
        return 5
    if x=='DODGE':
        return 6
    if x=='FORD':
        return 7
    if x=='GMC':
        return 8
    if x=='HONDA':
        return 9
    if x=='HYUNDAI':
        return 10
    if x=='INFINITI':
        return 11
    if x=='ISUZU':
        return 12
    if x=='JEEP':
        return 13
    if x=='KIA':
        return 14
    if x=='LEXUS':    
        return 15
    if x=='LINCOLN':
        return 16
    if x=='MAZDA':
        return 17
    if x=='MERCURY':
        return 18
    if x=='MINI':
        return 19
    if x=='MITSUBISHI':    
        return 20
    if x=='NISSAN':    
        return 21
    if x=='OLDSMOBILE':    
        return 22
    if x=='PLYMOUTH':
        return 23
    if x=='PONTIAC':    
        return 24
    if x=='SATURN':    
        return 25
    if x=='SCION':
        return 26
    if x=='SUBARU':    
        return 27
    if x=='SUZUKI':    
        return 28
    if x=='TOYOTA':    
        return 29
    if x=='TOYOTA SCION':    
        return 30
    if x=='VOLKSWAGEN':
        return 31
    if x=='VOLVO':    
        return 32
    else:
        return 0


def transmission_to_numeric(z):
    if z=='AUTO':
        return 1
    if z=='MANUAL':
        return 2
    else:
        return 1
    
    
def vnst_to_numeric(x):
    if x=='AL':
        return 1
    if x=='AR':
        return 2
    if x=='AZ':
        return 3
    if x=='CA':
        return 4
    if x=='CO':
        return 5
    if x=='FL':
        return 6
    if x=='GA':
        return 7
    if x=='IA':
        return 8
    if x=='ID':
        return 9
    if x=='IL':
        return 10
    if x=='IN':
        return 11
    if x=='KY':
        return 12
    if x=='LA':
        return 13
    if x=='MA':
        return 14
    if x=='MD':    
        return 15
    if x=='MI':
        return 16
    if x=='MN':
        return 17
    if x=='MO':
        return 18
    if x=='MS':
        return 19
    if x=='NC':    
        return 20
    if x=='NE':    
        return 21
    if x=='NH':    
        return 22
    if x=='NJ':
        return 23
    if x=='NM':    
        return 24
    if x=='NV':    
        return 25
    if x=='NY':
        return 26
    if x=='OH':    
        return 27
    if x=='OK':    
        return 28
    if x=='OR':    
        return 29
    if x=='PA':    
        return 30
    if x=='SC':
        return 31
    if x=='TN':    
        return 32
    if x=='TX':    
        return 33
    if x=='UT':    
        return 34
    if x=='VA':    
        return 35
    if x=='WA':
        return 36
    if x=='WV':    
        return 37
    else:
        return 0    
    
def nationality_to_numeric(r):
    if r=='AMERICAN':
        return 1
    if r=='ASIAN':
        return 2
    if r=='OTHER ASIAN':
        return 3
    if r=='TOP LINE ASIAN':
        return 4
    else:
        return 0